### ISSUE TITLE
A problem Need Help!!

### ISSUE THREAD

**Issue by Fire7ly** [SanderKlootwijk/vollanotchfix#2]
I'm fork your repo as you suggested!
but I cant fix notification panel it goes big instead of fix 
my device is Realme c3 RMX2020
720 X 1600 resolution
my forked repo ==>> https://github.com/Fire7ly/unity8-notch-hax
![photo_2021-11-08_13-59-16](https://user-images.githubusercontent.com/78557199/140709672-76364b12-4925-41e9-8c82-5b1304becaa9.jpg)
n

**Comment by SanderKlootwijk** [comment]
Hello Fire7ly, I see you have forked JamiKettunen's repo (https://github.com/JamiKettunen/unity8-notch-hax), which is a fork of my original repo (where you have opened an issue right now). Jami continued and improved this patch, so I suggest to contact him for this issue.

**Comment by Fire7ly** [comment]
actually you can say me noob im open a issue there but idk how it come here!!
