### ISSUE TITLE
Trying to apply the fix broke the phone

### ISSUE THREAD

**Issue by pparent76** [SanderKlootwijk/vollanotchfix#3]
Hi,

I tried to apply the fix, unfortunately now the phone is unusable:

file://usr/share/unity8/Orient...qml:280:9: Cannot asign to non-existant poperty "lightIndicators"

No idea how to restore the phone, I guess I will have to re-flash it.

**Comment by pparent76** [comment]
I think it would be good to mention in the readme that this is not compatible with the current version, and that one should follow the method described here: https://forums.ubports.com/topic/5351/easy-fix-possible-issue-of-not-readable-time-on-volla-phone-display-with-rounded-corners/22

**Comment by SanderKlootwijk** [comment]
Hi @pparent76, I'm sorry that the patch broke your UT installation. You should be able to easily reflash it with the UBports Installer, without erasing userdata to keep your files. As you post in the URL above, Jame Kettunen made an improved version of the patch, with a more user-friendly install procedure. It's a good idea to mention this in the readme of this repository.

**Comment by pparent76** [comment]
No worries it was a new device that I received this morning, and I reflashed it successfully!

**Comment by SanderKlootwijk** [comment]
Happy to hear that :)
